### ISSUE TITLE
Cannot pass a settings or ticket, To change the copies or paper size.

### ISSUE THREAD

**Issue by Gabszy10** [brickclick/node-gcp#7]
I tried to add this in the code, Because all other resources that I have found is they are passing a ticket to pass the printer settings, Maybe you need to change the page size, or change the copies of paper that will get print.

So here in my example code below, I pass a ticket with a copies = 3, I am expecting a result in my printer to print 3, But all I am getting is 1. But the main reason that I am passing a ticket is to change the paper size to A5 or B6 Paper.

return preq({
    method: "POST",
    uri: "https://www.google.com/cloudprint/submit",
    form: {
      title: "Print job title",
      content:
        "test print",
      ticket: {
        version: "1.0",
        print: {
          copies: {
            copies: 3
          },
          page_orientation: {
            type: 0
          },
          margins: {
            top_microns: 0,
            bottom_microns: 0,
            left_microns: 0,
            right_microns: 0
          }
        }
      },

      contentType: "url", //optional, default = url
      printerid: xxxxxxxxxxxxx,
      tags: ["tag1", "tag2"] //optional, default = [],
    },
    headers: {
      "X-CloudPrint-Proxy": "node-gcp",
      Authorization: "OAuth " + this.options.accessToken
    },
    json: true
  })
    .then(function(result) {
      return result;
    })
    .nodeify(cb);
});

**Comment by t3rminus** [comment]
@Gabszy10 You can pass a ticket in the `settings` parameter of the print function:

```javascript
printClient.print(printer.id, content, contentType, jobName, settings);
```

The trick is ***the ticket must be a JSON-encoded string***. Google Cloud Print's API is not clear on this, and it took me a while to figure out.

```javascript
const settings = { ticket: JSON.stringify(ticket) };
printClient.print(printer.id, content, contentType, jobName, settings);
```

No modification to the code should be necessary. Let me know if this works for you.

**Comment by Gabszy10** [comment]
Thankyou so much Kevin! I'll try this later, It's 9 AM in here, We can only test 6PM onwards.

But I still have a question, I think I tried that already and I think It gives me an error like

Failed to parse the print job\'s print ticket after I did JSON.stringify or something.

Have you tried testing this? And get 3 copies?

**Comment by Gabszy10** [comment]
Look at this Kevin, No ticket has been passed in the form nor jobName.

`settings.title =
    settings.title || title || "UNTITLED JOB " + shortid.generate();
  settings.contentType = settings.contentType || contentType;
  settings.printerid = settings.printerid || printerId;
  settings.content = settings.content || content;

  return preq({
    method: "POST",
    uri: "https://www.google.com/cloudprint/submit",
    form: settings,
    headers: {
      "X-CloudPrint-Proxy": "node-gcp",
      Authorization: "OAuth " + this.options.accessToken
    },
    json: true
  })`

**Comment by t3rminus** [comment]
`settings` is the form object that is serialized and submitted to GCP. Anything it contains is automatically forwarded to Google. This is not specific to tickets (which is why there is no code specifically for it), but if you read through it again, you'll see that I'm extending the `settings` object, and then submitting the entire thing, tickets included.

I've used tickets extensively in the past for custom paper sizes, and had no issues. Make sure you double-check your code against what I've written above, and make sure your ticket conforms to Google's ticket format here: https://developers.google.com/cloud-print/docs/cdd#cjt

**Comment by Gabszy10** [comment]
Oh! I didn't see this part.

settings = settings || {};

Alright, Thankyou Kevin! I'll try this later, and will let you know if this thing works out.

**Comment by t3rminus** [comment]
I've added this documentation to the README (and added a missing brace to the code I posted above).

I'm going to close this issue. If you're still having trouble, feel free to comment and I can reopen and investigate further.

**Comment by Gabszy10** [comment]
Hi! The settings is now working, But when I'm adding a vendor id, to force tha paper size to be A6, A5, B6 etc.

media_size: {
                  height_microns: 200000,
                  vendor_id: "ISO_A5"
                },

I'm getting an error of This is not a correnct print ticket :(

**Comment by Gabszy10** [comment]
It's fixed just need to add is_continuous_feed: false :D
